### ISSUE TITLE
TypeError: undefined is not a function (does this when trying to lint scala files

### ISSUE THREAD

**Issue by grundyboy34** [AtomLinter/linter-scalac#5]
When atom attempts to opens a .scala file I get this error. 
Also, my Scalac  path is set to `C:\Scala\bin` which contains scalac

```
TypeError: undefined is not a function
  at LinterScalac.Linter (c:\Users\Jerry\.atom\packages\linter\lib\linter.coffee:54:33)
  at new LinterScalac (c:\Users\Jerry\.atom\packages\linter-scalac\lib\linter-scalac.coffee:19:3)
  at LinterView.initLinters (c:\Users\Jerry\.atom\packages\linter\lib\linter-view.coffee:51:27)
  at new LinterView (c:\Users\Jerry\.atom\packages\linter\lib\linter-view.coffee:33:6)
  at c:\Users\Jerry\.atom\packages\linter\lib\init.coffee:83:24
  at c:\Program Files\Atom\resources\app\src\workspace.js:276:16
  at c:\Program Files\Atom\resources\app\src\workspace.js:321:18
  at Emitter.module.exports.Emitter.emit (c:\Program Files\Atom\resources\app\node_modules\event-kit\lib\emitter.js:71:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (c:\Program Files\Atom\resources\app\src\pane-container.js:361:27)
  at c:\Program Files\Atom\resources\app\src\pane-container.js:348:26
  at Emitter.module.exports.Emitter.emit (c:\Program Files\Atom\resources\app\node_modules\event-kit\lib\emitter.js:71:11)
  at Pane.module.exports.Pane.addItem (c:\Program Files\Atom\resources\app\src\pane.js:320:20)
  at Pane.module.exports.Pane.activateItem (c:\Program Files\Atom\resources\app\src\pane.js:299:14)
  at c:\Program Files\Atom\resources\app\src\workspace.js:481:16
  at _fulfilled (c:\Program Files\Atom\resources\app\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (c:\Program Files\Atom\resources\app\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (c:\Program Files\Atom\resources\app\node_modules\q\q.js:749:13)
  at c:\Program Files\Atom\resources\app\node_modules\q\q.js:509:49
  at flush (c:\Program Files\Atom\resources\app\node_modules\q\q.js:108:17)
  at process._tickCallback (node.js:378:11)
```

**Comment by grundyboy34** [comment]
This seems to be from linter itself and I was using an older version of Atom. I updated Atom but now linter-scalac doesn't show up in packages, perhaps it's not up to date with the current build of Atom?

**Comment by Arcanemagus** [comment]
I'm marking this as closed since the linter has been completely re-written since this was filed. I'm sorry nobody responded to your issue before now. If you are still having problems please file a new issue, thanks!
