### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by phammer** [AtomLinter/linter-scalac#6]
How to reproduce:

1. open atom
2. open any scala file => ERROR

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-scalac](https://github.com/AtomLinter/linter-scalac) package, v0.3.3

### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At child_process.js:1156

Error: spawn ENAMETOOLONG
  at exports._errnoException (util.js:746:11)
  at ChildProcess.spawn (child_process.js:1156:11)
  at exports.spawn (child_process.js:989:9)
  at Object.exports.execFile (child_process.js:683:15)
  at Object.module.(anonymous function) [as execFile] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:448:20)
  at exports.exec (child_process.js:651:18)
  at LinterScalac.lintFile (/Users/ph/.atom/packages/linter-scalac/lib/linter-scalac.coffee:44:3)
  at /Users/ph/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /Users/ph/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -3:10.7 application:new-file (atom-text-editor.editor)
     -3:10.0 core:paste (atom-text-editor.editor)
     -2:20.3 editor:newline (atom-text-editor.editor)
     -1:47.2 find-and-replace:show (atom-text-editor.editor)
  3x -1:45.4 core:backspace (atom-text-editor.editor.mini)
  4x -1:44.6 core:confirm (atom-text-editor.editor.mini)
  2x -0:38.2 core:paste (atom-text-editor#linter-scalac.scalacOptions.editor.mini)
     -0:18.3 core:save (atom-text-editor#linter-scalac.scalacExecutablePath.editor.mini)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "build",
      "nezasa-inventory.min.js",
      "nezasa-platform.min.js",
      "nezasa-admin.min.js"
    ],
    "disabledPackages": [
      "htmlhint"
    ],
    "projectHome": "/Users/ph/nezasa/code/platform"
  },
  "linter-scalac": {
    "scalacOptions": "-Xlint -P:wartremover:traverser:org.brianmckenna.wartremover.warts.Unsafe",
    "scalacExecutablePath": "/usr/local/bin"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.2
atom-handlebars, v0.4.0
auto-update-packages, v0.2.2
autoclose-html, v0.14.0
color-picker, v1.4.4
language-scala, v1.1.0
linter, v0.10.1
linter-scalac, v0.3.3
pretty-json, v0.3.2
space-tab, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by Arcanemagus** [comment]
@phammer Are you still experiencing this?

**Comment by phammer** [comment]
@Arcanemagus : sorry for the late reply. I re-tested the issue, now with the following versions:

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [linter-scalac](https://github.com/AtomLinter/linter-scalac) package, v1.3.1

The error doesn't occur anymore. All fine.

**Comment by Arcanemagus** [comment]
Glad to hear it :wink:.
